name: Integrate
on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]
jobs:
  lint:
    if: ${{ !startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@current
      - run: npm run lint
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/')}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin
          - os: windows-latest
            platform: win32
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    steps:
      - uses: holepunchto/actions/node-base@current
      - run: npm install -g bare-runtime
      - run: npm test
  trigger_canary:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: trigger canary
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CANARY_DISPATCH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/holepunchto/canary-tests/dispatches \
          -d '{"event_type":"triggered-by-${{ github.event.repository.name }}-${{ github.ref_name }}"}'
