name: Test

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  lint:
    if: ${{ !startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with: { node-version: lts/* }
      - run: npm install
      - run: npm run lint

  test-node:
    if: ${{ !startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    name: Node
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with: { node-version: lts/* }
      - run: npm i
      - run: npm run test:node

  test-bare:
    if: ${{ !startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    name: Bare
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with: { node-version: lts/* }
      - run: npm i
      - run: npm i -g bare-runtime
      - run: npm run test:bare

  trigger_canary:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: trigger canary
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CANARY_DISPATCH_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/holepunchto/canary-tests/dispatches \
          -d '{"event_type":"triggered-by-${{ github.event.repository.name }}-${{ github.ref_name }}"}'
